### ISSUE TITLE
Cookie consent in Sainsbury sites 

### ISSUE THREAD

**Issue by galmoav** [GetEvinced/Consent-O-Matic#3]
the cookie consents in the following sites are not clicked through:

https://tuclothing.sainsburys.co.uk/

https://www.argos.co.uk/

Not tested bug of the same family:
https://www.habitat.co.uk/ 
https://www.nectar.com/

**Comment by shalev-kaveh** [comment]
The https://www.nectar.com/ cookie consent should be caught (it's the same provider as https://www.sainsburys.co.uk/)

Adding rules for the rest - it's in PR - I'll update once it's merged and all tested

**Comment by galmoav** [comment]
in their account (before the manual change you did) I could see that https://tuclothing.sainsburys.co.uk/browse/baby/accessories/c:840357/?clickOrigin=header:click:nav:baby:accessories-%26-essentials:accessories is not clicked 
for example (support+sainsbury) https://app.evinced.com/properties/b8a62751-b66c-451b-b0e2-74065e3aebc7/scans/075bb7d1-2703-4b6c-a2e3-92a5903cbc64/components/16db86e4?viewId=all
